oauth:
  cognito_redirect_uri: http://api.staging.kscale.dev/auth/login
dynamo:
  table_name: kscale-www-staging-cluster
site:
  homepage: https://dashboard-staging.kscale.dev
  artifact_base_url: https://stagingassets.kscale.dev/
  enable_test_endpoint: true
