name: CI Checks (Linting and Tests)

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Restore cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: tests
          restore-keys: |
            tests

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python package
        run: |
          pip install --upgrade --upgrade-strategy eager -e '.[dev]'

      - name: Run linting and type checks
        run: |
          mkdir -p .mypy_cache
          make lint

      - name: Run unit tests
        run: |
          make test

      - name: Save cache
        uses: actions/cache/save@v3
        if: github.ref == 'refs/heads/master'
        with:
          path: |
            ${{ env.pythonLocation }}
            .mypy_cache/
          key: tests
